/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kickscorner;

import backend.GetData;
import backend.KicksCornerInsert;
import backend.KicksCornerShow1;

import classSQL.Customer;
import classSQL.Employee;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static kickscorner.KicksCorner.employeeModel;
import static kickscorner.KicksCorner.membershipModel;

/**
 *
 * @author Asus
 */
public class RegisterCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public RegisterCustomer() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/KicksCornerIcon.png")));
        initComponents();

        RegisterCustomer.this.setDefaultCloseOperation(RegisterCustomer.DISPOSE_ON_CLOSE);
    }

    public JTextField getJTextFieldPhoneNewCustomer() {
        return jTextFieldPhoneNewCustomer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jPanelRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNameNewCustomer = new javax.swing.JTextField();
        jTextFieldPhoneNewCustomer = new javax.swing.JTextField();
        jButtonRegisterCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kicks Corner");
        setBackground(new java.awt.Color(153, 0, 0));

        jPanelRegister.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Customer");

        jTextFieldNameNewCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNameNewCustomerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNameNewCustomerFocusLost(evt);
            }
        });
        jTextFieldNameNewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNameNewCustomerMouseClicked(evt);
            }
        });
        jTextFieldNameNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameNewCustomerActionPerformed(evt);
            }
        });

        jTextFieldPhoneNewCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneNewCustomerFocusGained(evt);
            }
        });
        jTextFieldPhoneNewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPhoneNewCustomerMouseClicked(evt);
            }
        });
        jTextFieldPhoneNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNewCustomerActionPerformed(evt);
            }
        });

        jButtonRegisterCustomer.setBackground(new java.awt.Color(134, 182, 246));
        jButtonRegisterCustomer.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButtonRegisterCustomer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegisterCustomer.setText("Add");
        jButtonRegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterCustomerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Name");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Phone");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 1, 0, 0));

        javax.swing.GroupLayout jPanelRegisterLayout = new javax.swing.GroupLayout(jPanelRegister);
        jPanelRegister.setLayout(jPanelRegisterLayout);
        jPanelRegisterLayout.setHorizontalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNameNewCustomer)
                    .addComponent(jTextFieldPhoneNewCustomer)
                    .addComponent(jButtonRegisterCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelRegisterLayout.setVerticalGroup(
            jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegisterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNameNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPhoneNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameNewCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameNewCustomerActionPerformed

    private void jTextFieldPhoneNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNewCustomerActionPerformed
        jButtonRegisterCustomer.doClick();
    }//GEN-LAST:event_jTextFieldPhoneNewCustomerActionPerformed

    private void jButtonRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterCustomerActionPerformed
        Object[] customerInfo = GetData.getNewCustomer(jTextFieldNameNewCustomer, jTextFieldPhoneNewCustomer);
        String name = (String) customerInfo[0];
        String phone = (String) customerInfo[1];
        
        if (phone.matches("^0[0-9]{9}$")) {         
            Customer newCustomer = new Customer(name, phone);
            System.out.println(newCustomer.getCustomerName() + newCustomer.getCustomerPhone());
            KicksCornerInsert.insertMembership(newCustomer);
            JOptionPane.showMessageDialog(null, "Register success");
            RegisterCustomer.this.dispose();
            KicksCornerShow1.showNewRegisterCustomer(membershipModel, phone);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a valid phone number (10 digits).", "Invalid Phone Number", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonRegisterCustomerActionPerformed

    private void jTextFieldNameNewCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameNewCustomerFocusGained

    }//GEN-LAST:event_jTextFieldNameNewCustomerFocusGained

    private void jTextFieldNameNewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameNewCustomerMouseClicked
        jTextFieldNameNewCustomer.setFocusable(true);
        jTextFieldNameNewCustomer.requestFocus();
    }//GEN-LAST:event_jTextFieldNameNewCustomerMouseClicked

    private void jTextFieldPhoneNewCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNewCustomerFocusGained

    }//GEN-LAST:event_jTextFieldPhoneNewCustomerFocusGained

    private void jTextFieldPhoneNewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNewCustomerMouseClicked
        jTextFieldPhoneNewCustomer.setFocusable(true);
        jTextFieldPhoneNewCustomer.requestFocus();
    }//GEN-LAST:event_jTextFieldPhoneNewCustomerMouseClicked

    private void jTextFieldNameNewCustomerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNameNewCustomerFocusLost

    }//GEN-LAST:event_jTextFieldNameNewCustomerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRegisterCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelRegister;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNameNewCustomer;
    private javax.swing.JTextField jTextFieldPhoneNewCustomer;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
